apiVersion: 1

datasources:
  - name: Crystallization InfluxDB
    uid: crystallization-influxdb
    type: influxdb
    access: proxy
    orgId: 1
    url: http://influxdb:8086
    isDefault: true
    editable: false
    version: 1
    jsonData:
      version: Flux
      organization: $INFLUX_ORG
      defaultBucket: $INFLUX_BUCKET
      tlsSkipVerify: false
      timeInterval: 1s
    secureJsonData:
      token: $INFLUX_TOKEN
